"""add phone to user and customer snapshot fields to order

Revision ID: 66233b538e95
Revises: fd7ce483d123
Create Date: 2026-03-12 22:42:59.872840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66233b538e95'
down_revision = 'fd7ce483d123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
